### ISSUE TITLE
Upload documentation to Hackage

### ISSUE THREAD

**Issue by ChShersh** [massysett/rainbow#10]
I don't see documentation on Hackage for couple latest version sof `rainbow` package:

* http://hackage.haskell.org/package/rainbow

This makes reading tutorial for this package harder. 
If Hackage doesn't build documentation for your package, you can upload documentation manually. For example, with tool called `hup`:

* https://github.com/phlummox/hup

**Comment by massysett** [comment]
The docs are on Stackage; please look there.  Thanks.

**Comment by ChShersh** [comment]
@massysett Well, at least you could put link to Stackage in your README. Now I see only link to Hackage. So if I want to see documentation, I follow the link and go to Hackage. Then I see that there's no documentation. So I had to assume that `rainbow` package is on Stackage, go to Stackage manually, and then find `rainbow` package there. This is not a convenient workflow at all. You can even go further make links as README badges. See example how it's done in this package:

* https://github.com/serokell/universum#universum

**Comment by massysett** [comment]
Can you send a pull request?  Thanks.
