### ISSUE TITLE
compile error with GHC 7.8

### ISSUE THREAD

**Issue by hvr** [massysett/rainbow#5]
The `.cabal` file claims compatibility with `base >= 4.7.0.0 && < 5`

However, with `base-4.7` there's a compile-failure:

```
[1 of 3] Compiling Rainbow.Types    ( lib/Rainbow/Types.hs, dist/dist-sandbox-8ea63412/build/Rainbow/Types.o )

lib/Rainbow/Types.hs:34:10:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Prelude)
xcabal: Error: some packages failed to install:
rainbow-0.28.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

I have edited `rainbox-0.28.0.0` on Hackage to fix this (and while at it I also fixed the unnecessarily restricting `cabal-version` declaration): https://hackage.haskell.org/package/rainbow-0.28.0.0/revisions/

**Comment by massysett** [comment]
Fixed in version 0.28.0.2, thanks very much for the report.
