### ISSUE TITLE
Switch back to 'microlens' from 'lens-simple'

### ISSUE THREAD

**Issue by ChShersh** [massysett/rainbow#9]
`microlens` library has documentation on Hackage so I guess now everything is ok with this library. I'd prefer to use `rainbow` more if it would depend on `microlens` instead of `lens-simple` because `microlens` has almost none dependencies.

**Comment by massysett** [comment]
Hi,

Thanks for commenting.  The dependency graph on lens-simple is small enough, and the lenses are fully compatible.  Thanks.  --Omari
